GET http://localhost:3000/register


###

POST http://localhost:3000/register
Content-Type: application/json

{
    "firstName": "ibrahim",
    "secondName": "kabiru",
    "email": "ibrahimkabir@yahoo.com",
    "password": "anotherOne",
    "dateOfBirth": "28/2/2003",
    "phoneNumber": "08033992832",
    "state": "sokoto"
  }